export enum LEAVE_REQUEST_PERMISSION {
  READ_LEAVE_REQUEST = 'READ_LEAVE_REQUEST',
  CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST',
  UPDATE_LEAVE_REQUEST = 'UPDATE_LEAVE_REQUEST',
  DELETE_LEAVE_REQUEST = 'DELETE_LEAVE_REQUEST'
}
