export enum ReasonTemplateTypeEnum {
  ALL = 'ALL',
  EMPLOYEE_MOVEMENT = 'EMPLOYEE_MOVEMENT',
  EMPLOYEE_RESIGNATION = 'EMPLOYEE_RESIGNATION',
  EMPLOYEE_WARNING = 'EMPLOYEE_WARNING',
  MISSED_SCAN_REQUEST = 'MISSED_SCAN_REQUEST',
  OVERTIME_REQUEST = 'OVERTIME_REQUEST',
  MISSION_REQUEST = 'MISSION_REQUEST',
  LEAVE = 'LEAVE',
  OTHER = 'OTHER'
}
