import * as PERMISSION from '../../../../shared-resources/ts/enum/permission';

export const ROLE_PERMISSION_PERMISSION = {
  GET_ROLE_PERMISSION: [
    PERMISSION.ROLE_PERMISSION_PERMISSION.READ_ROLE_PERMISSION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ],
  DELETE_ROLE_PERMISSION: [
    PERMISSION.ROLE_PERMISSION_PERMISSION.DELETE_ROLE_PERMISSION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  UPDATE_ROLE_PERMISSION: [
    PERMISSION.ROLE_PERMISSION_PERMISSION.UPDATE_ROLE_PERMISSION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  CREATE_ROLE_PERMISSION: [
    PERMISSION.ROLE_PERMISSION_PERMISSION.CREATE_ROLE_PERMISSION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ]
};
