import * as PERMISSION from '../../../../shared-resources/ts/enum/permission';

export const AUDIT_LOG_PERMISSION = {
  GET_AUDIT_LOG: [
    PERMISSION.AUDIT_LOG_PERMISSION.READ_AUDIT_LOG,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ]
};
