export const codeValues = [
  {
    name: 'COUNTRY',
    sub: {
      READ_COUNTRY: 'READ_COUNTRY',
      CREATE_COUNTRY: 'CREATE_COUNTRY',
      UPDATE_COUNTRY: 'UPDATE_COUNTRY',
      DELETE_COUNTRY: 'DELETE_COUNTRY'
    }
  },
  {
    name: 'CURRENCY',
    sub: {
      READ_CURRENCY: 'READ_CURRENCY',
      CREATE_CURRENCY: 'CREATE_CURRENCY',
      UPDATE_CURRENCY: 'UPDATE_CURRENCY',
      DELETE_CURRENCY: 'DELETE_CURRENCY'
    }
  },
  {
    name: 'NATIONALITY',
    sub: {
      READ_NATIONALITY: 'READ_NATIONALITY',
      CREATE_NATIONALITY: 'CREATE_NATIONALITY',
      UPDATE_NATIONALITY: 'UPDATE_NATIONALITY',
      DELETE_NATIONALITY: 'DELETE_NATIONALITY'
    }
  },
  {
    name: 'IMMIGRATION_STATUS',
    sub: {
      READ_IMMIGRATION_STATUS: 'READ_IMMIGRATION_STATUS',
      CREATE_IMMIGRATION_STATUS: 'CREATE_IMMIGRATION_STATUS',
      UPDATE_IMMIGRATION_STATUS: 'UPDATE_IMMIGRATION_STATUS',
      DELETE_IMMIGRATION_STATUS: 'DELETE_IMMIGRATION_STATUS'
    }
  },
  {
    name: 'CONTRACT_TYPE',
    sub: {
      READ_CONTRACT_TYPE: 'READ_CONTRACT_TYPE',
      CREATE_CONTRACT_TYPE: 'CREATE_CONTRACT_TYPE',
      UPDATE_CONTRACT_TYPE: 'UPDATE_CONTRACT_TYPE',
      DELETE_CONTRACT_TYPE: 'DELETE_CONTRACT_TYPE'
    }
  },
  {
    name: 'RELATIONSHIP',
    sub: {
      READ_RELATIONSHIP: 'READ_RELATIONSHIP',
      CREATE_RELATIONSHIP: 'CREATE_RELATIONSHIP',
      UPDATE_RELATIONSHIP: 'UPDATE_RELATIONSHIP',
      DELETE_RELATIONSHIP: 'DELETE_RELATIONSHIP'
    }
  },
  {
    name: 'EDUCATION_TYPE',
    sub: {
      READ_EDUCATION_TYPE: 'READ_EDUCATION_TYPE',
      CREATE_EDUCATION_TYPE: 'CREATE_EDUCATION_TYPE',
      UPDATE_EDUCATION_TYPE: 'UPDATE_EDUCATION_TYPE',
      DELETE_EDUCATION_TYPE: 'DELETE_EDUCATION_TYPE'
    }
  },
  {
    name: 'LANGUAGE',
    sub: {
      READ_LANGUAGE: 'READ_LANGUAGE',
      CREATE_LANGUAGE: 'CREATE_LANGUAGE',
      UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
      DELETE_LANGUAGE: 'DELETE_LANGUAGE'
    }
  },
  {
    name: 'DOCUMENT_TYPE',
    sub: {
      READ_DOCUMENT_TYPE: 'READ_DOCUMENT_TYPE',
      CREATE_DOCUMENT_TYPE: 'CREATE_DOCUMENT_TYPE',
      UPDATE_DOCUMENT_TYPE: 'UPDATE_DOCUMENT_TYPE',
      DELETE_DOCUMENT_TYPE: 'DELETE_DOCUMENT_TYPE'
    }
  },
  {
    name: 'SKILL',
    sub: {
      READ_SKILL: 'READ_SKILL',
      CREATE_SKILL: 'CREATE_SKILL',
      UPDATE_SKILL: 'UPDATE_SKILL',
      DELETE_SKILL: 'DELETE_SKILL'
    }
  },
  {
    name: 'RESIGNATION_TYPE',
    sub: {
      READ_RESIGNATION_TYPE: 'READ_RESIGNATION_TYPE',
      CREATE_RESIGNATION_TYPE: 'CREATE_RESIGNATION_TYPE',
      UPDATE_RESIGNATION_TYPE: 'UPDATE_RESIGNATION_TYPE',
      DELETE_RESIGNATION_TYPE: 'DELETE_RESIGNATION_TYPE'
    }
  },
  {
    name: 'WARNING_TYPE',
    sub: {
      READ_WARNING_TYPE: 'READ_WARNING_TYPE',
      CREATE_WARNING_TYPE: 'CREATE_WARNING_TYPE',
      UPDATE_WARNING_TYPE: 'UPDATE_WARNING_TYPE',
      DELETE_WARNING_TYPE: 'DELETE_WARNING_TYPE'
    }
  },
  {
    name: 'TRAINING',
    sub: {
      READ_TRAINING: 'READ_TRAINING',
      CREATE_TRAINING: 'CREATE_TRAINING',
      UPDATE_TRAINING: 'UPDATE_TRAINING',
      DELETE_TRAINING: 'DELETE_TRAINING'
    }
  },
  {
    name: 'GENDER',
    sub: {
      READ_GENDER: 'READ_GENDER',
      CREATE_GENDER: 'CREATE_GENDER',
      UPDATE_GENDER: 'UPDATE_GENDER',
      DELETE_GENDER: 'DELETE_GENDER'
    }
  },
  {
    name: 'MARITAL_STATUS',
    sub: {
      READ_MARITAL_STATUS: 'READ_MARITAL_STATUS',
      CREATE_MARITAL_STATUS: 'CREATE_MARITAL_STATUS',
      UPDATE_MARITAL_STATUS: 'UPDATE_MARITAL_STATUS',
      DELETE_MARITAL_STATUS: 'DELETE_MARITAL_STATUS'
    }
  }
];
