export const employeeResignationAndDayOffRequests = [
  {
    name: 'EMPLOYEE_MODULE',
    sub: {
      name: 'EMPLOYEE_RESIGNATION',
      sub: {
        READ_EMPLOYEE_RESIGNATION: 'READ_EMPLOYEE_RESIGNATION',
        CREATE_EMPLOYEE_RESIGNATION: 'CREATE_EMPLOYEE_RESIGNATION',
        UPDATE_EMPLOYEE_RESIGNATION: 'UPDATE_EMPLOYEE_RESIGNATION',
        DELETE_EMPLOYEE_RESIGNATION: 'DELETE_EMPLOYEE_RESIGNATION'
      }
    }
  },
  {
    name: 'LEAVE_MODULE',
    sub: {
      name: 'DAY_OFF_REQUEST',
      sub: {
        READ_DAY_OFF_REQUEST: 'READ_DAY_OFF_REQUEST',
        CREATE_DAY_OFF_REQUEST: 'CREATE_DAY_OFF_REQUEST',
        UPDATE_DAY_OFF_REQUEST: 'UPDATE_DAY_OFF_REQUEST',
        DELETE_DAY_OFF_REQUEST: 'DELETE_DAY_OFF_REQUEST'
      }
    }
  }
];
