export enum BulkTypeEnum {
  EMPLOYEE = 'EMPLOYEE',
  EMPLOYEE_RESIGNATION = 'RESIGNATION_REQUEST',
  LEAVE_REQUEST = 'LEAVE_REQUEST',
  DAY_OFF_REQUEST = 'DAY_OFF_REQUEST',
  MISSED_SCAN = 'MISSED_SCAN',
  WARNING = 'WARNING'
}
