export enum ATTENDANCE_REPORT_PERMISSION {
  READ_ATTENDANCE_REPORT = 'READ_ATTENDANCE_REPORT',
  CREATE_ATTENDANCE_REPORT = 'CREATE_ATTENDANCE_REPORT',
  UPDATE_ATTENDANCE_REPORT = 'UPDATE_ATTENDANCE_REPORT',
  DELETE_ATTENDANCE_REPORT = 'DELETE_ATTENDANCE_REPORT'
}
