export enum MISSED_SCAN_REQUEST_PERMISSION {
  READ_MISSED_SCAN_REQUEST = 'READ_MISSED_SCAN_REQUEST',
  CREATE_MISSED_SCAN_REQUEST = 'CREATE_MISSED_SCAN_REQUEST',
  UPDATE_MISSED_SCAN_REQUEST = 'UPDATE_MISSED_SCAN_REQUEST',
  DELETE_MISSED_SCAN_REQUEST = 'DELETE_MISSED_SCAN_REQUEST'
}
