export enum OVERTIME_REQUEST_TYPE_PERMISSION {
  READ_OVERTIME_REQUEST_TYPE = 'READ_OVERTIME_REQUEST_TYPE',
  CREATE_OVERTIME_REQUEST_TYPE = 'CREATE_OVERTIME_REQUEST_TYPE',
  UPDATE_OVERTIME_REQUEST_TYPE = 'UPDATE_OVERTIME_REQUEST_TYPE',
  DELETE_OVERTIME_REQUEST_TYPE = 'DELETE_OVERTIME_REQUEST_TYPE'
}
