import * as PERMISSION from '../../../../shared-resources/ts/enum/permission';

export const EMPLOYEE_RESIGNATION = {
  GET_EMPLOYEE_RESIGNATION: [
    PERMISSION.EMPLOYEE_RESIGNATION_PERMISSION.READ_EMPLOYEE_RESIGNATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ],
  DELETE_EMPLOYEE_RESIGNATION: [
    PERMISSION.EMPLOYEE_RESIGNATION_PERMISSION.DELETE_EMPLOYEE_RESIGNATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  UPDATE_EMPLOYEE_RESIGNATION: [
    PERMISSION.EMPLOYEE_RESIGNATION_PERMISSION.UPDATE_EMPLOYEE_RESIGNATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  CREATE_EMPLOYEE_RESIGNATION: [
    PERMISSION.EMPLOYEE_RESIGNATION_PERMISSION.CREATE_EMPLOYEE_RESIGNATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ]
};
