import * as PERMISSION from '../../../../shared-resources/ts/enum/permission';

export const ROLE_PERMISSION = {
  GET_ROLE_PERMISSION: [
    PERMISSION.ROLE_PERMISSION.READ_ROLE,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ],
  DELETE_ROLE_PERMISSION: [
    PERMISSION.ROLE_PERMISSION.DELETE_ROLE,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  UPDATE_ROLE_PERMISSION: [
    PERMISSION.ROLE_PERMISSION.UPDATE_ROLE,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  CREATE_ROLE_PERMISSION: [
    PERMISSION.ROLE_PERMISSION.CREATE_ROLE,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ]
};
