export enum AUTHENTICATION_PERMISSION {
  'READ_AUTEHNTICATION' = 'READ_AUTEHNTICATION',
  'CREATE_AUTHENTICATION' = 'CREATE_AUTHENTICATION',
  'UPDATE_AUTHENTICATION' = 'UPDATE_AUTHENTICATION',
  'DELETE_AUTHENTICATION' = 'DELETE_AUTHENTICATION'
}
