export enum PERMISSION {
  'READ_PERMISSION' = 'READ_PERMISSION',
  'CREATE_PERMISSION' = 'CREATE_PERMISSION',
  'DELETE_PERMISSION' = 'DELETE_PERMISSION',
  'UPDATE_PERMISSION' = 'UPDATE_PERMISSION'
}
