export enum ROLE_PERMISSION_PERMISSION {
  'READ_ROLE_PERMISSION' = 'READ_ROLE_PERMISSION',
  'UPDATE_ROLE_PERMISSION' = 'UPDATE_ROLE_PERMISSION',
  'DELETE_ROLE_PERMISSION' = 'DELETE_ROLE_PERMISSION',
  'CREATE_ROLE_PERMISSION' = 'CREATE_ROLE_PERMISSION'
}
