import * as PERMISSION from '../../shared-resources/ts/enum/permission';

export const EMPLOYEE_MASTER_INFORMATION = {
  GET_EMPLOYEE: [
    PERMISSION.EMPLOYEE_MASTER_INFORMATION_PERMISSION
      .READ_EMPLOYEE_MASTER_INFORMATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ],
  DELETE_EMPLOYEE: [
    PERMISSION.EMPLOYEE_MASTER_INFORMATION_PERMISSION
      .DELETE_EMPLOYEE_MASTER_INFORMATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  UPDATE_EMPLOYEE: [
    PERMISSION.EMPLOYEE_MASTER_INFORMATION_PERMISSION
      .UPDATE_EMPLOYEE_MASTER_INFORMATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  CREATE_EMPLOYEE: [
    PERMISSION.EMPLOYEE_MASTER_INFORMATION_PERMISSION
      .CREATE_EMPLOYEE_MASTER_INFORMATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ]
};
