export enum GLOBAL_CONFIGURATION_DATATYPE {
  NUMBER = 'NUMBER',
  TEXT = 'TEXT',
  FLOAT = 'FLOAT',
  EMAIL = 'EMAIL',
  PASSWORD = 'PASSWORD',
  DATE = 'DATE',
  DATETIME = 'DATETIME',
  BOOLEAN = 'BOOLEAN'
}
