import * as PERMISSION from '../../../../shared-resources/ts/enum/permission';

export const GLOBAL_CONFIGURATION_PERMISSION = {
  GET_GLOBAL_CONFIGURATION: [
    PERMISSION.GLOBAL_CONFIGURATION_PERMISSION.READ_GLOBAL_CONFIGURATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ],
  UPDATE_GLOBAL_CONFIGURATION: [
    PERMISSION.GLOBAL_CONFIGURATION_PERMISSION.UPDATE_GLOBAL_CONFIGURATION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ]
};
