export enum REASON_TEPLATE_PERMISSION {
  READ_REASON_TEPLATE = 'READ_REASON_TEPLATE',
  UPDATE_REASON_TEPLATE = 'UPDATE_REASON_TEPLATE',
  CREATE_REASON_TEPLATE = 'CREATE_REASON_TEPLATE',
  DELETE_REASON_TEPLATE = 'DELETE_REASON_TEPLATE'
}
