export enum REQUEST_APPROVAL_WORKFLOW_PERMISSION {
  'READ_REQUEST_APPROVAL_WORKFLOW' = 'READ_REQUEST_APPROVAL_WORKFLOW',
  'CREATE_REQUEST_APPROVAL_WORKFLOW' = 'CREATE_REQUEST_APPROVAL_WORKFLOW',
  'DELETE_REQUEST_APPROVAL_WORKFLOW' = 'DELETE_REQUEST_APPROVAL_WORKFLOW',
  'UPDATE_REQUEST_APPROVAL_WORKFLOW' = 'UPDATE_REQUEST_APPROVAL_WORKFLOW'
}
