export enum CODE_VALUE_PERMISSION {
  'READ_CODE_VALUE' = 'READ_CODE_VALUE',
  'CREATE_CODE_VALUE' = 'CREATE_CODE_VALUE',
  'UPDATE_CODE_VALUE' = 'UPDATE_CODE_VALUE',
  'DELETE_CODE_VALUE' = 'DELETE_CODE_VALUE'
}
