export enum COMPANY_STRUCTURE_COMPONENT_PERMISSION {
  'READ_COMPANY_STRUCTURE_COMPONENT' = 'READ_COMPANY_STRUCTURE_COMPONENT',
  'CREATE_COMPANY_STRUCTURE_COMPONENT' = 'CREATE_COMPANY_STRUCTURE_COMPONENT',
  'UPDATE_COMPANY_STRUCTURE_COMPONENT' = 'UPDATE_COMPANY_STRUCTURE_COMPONENT',
  'DELETE_COMPANY_STRUCTURE_COMPONENT' = 'DELETE_COMPANY_STRUCTURE_COMPONENT'
}
