export enum EMPLOYEE_LANGUAGE_PERMISSION {
  READ_EMPLOYEE_LANGUAGE = 'READ_EMPLOYEE_LANGUAGE',
  CREATE_EMPLOYEE_LANGUAGE = 'CREATE_EMPLOYEE_LANGUAGE',
  UPDATE_EMPLOYEE_LANGUAGE = 'UPDATE_EMPLOYEE_LANGUAGE',
  DELETE_EMPLOYEE_LANGUAGE = 'DELETE_EMPLOYEE_LANGUAGE'
}
