export enum EMPLOYEE_MASTER_INFORMATION_PERMISSION {
  'READ_EMPLOYEE_MASTER_INFORMATION' = 'READ_EMPLOYEE_MASTER_INFORMATION',
  'CREATE_EMPLOYEE_MASTER_INFORMATION' = 'CREATE_EMPLOYEE_MASTER_INFORMATION',
  'UPDATE_EMPLOYEE_MASTER_INFORMATION' = 'UPDATE_EMPLOYEE_MASTER_INFORMATION',
  'DELETE_EMPLOYEE_MASTER_INFORMATION' = 'DELETE_EMPLOYEE_MASTER_INFORMATION'
}

export enum ATTACH_USER_TO_EMPLOYEE_PERMISSION {
  ATTACH_USER_TO_EMPLOYEE = 'ATTACH_USER_TO_EMPLOYEE'
}
