export enum EMPLOYEE_SKILL_PERMISSION {
  READ_EMPLOYEE_SKILL = 'READ_EMPLOYEE_SKILL',
  CREATE_EMPLOYEE_SKILL = 'CREATE_EMPLOYEE_SKILL',
  UPDATE_EMPLOYEE_SKILL = 'UPDATE_EMPLOYEE_SKILL',
  DELETE_EMPLOYEE_SKILL = 'DELETE_EMPLOYEE_SKILL'
}
