export enum EMPLOYEE_EMERGENCY_CONTACT_PERMISSION {
  READ_EMPLOYEE_EMERGENCY_CONTACT = 'READ_EMPLOYEE_EMERGENCY_CONTACT',
  CREATE_EMPLOYEE_EMERGENCY_CONTACT = 'CREATE_EMPLOYEE_EMERGENCY_CONTACT',
  UPDATE_EMPLOYEE_EMERGENCY_CONTACT = 'UPDATE_EMPLOYEE_EMERGENCY_CONTACT',
  DELETE_EMPLOYEE_EMERGENCY_CONTACT = 'DELETE_EMPLOYEE_EMERGENCY_CONTACT'
}
