export enum EMPLOYEE_CONTACT_PERMISSION {
  READ_EMPLOYEE_CONTACT = 'READ_EMPLOYEE_CONTACT',
  CREATE_EMPLOYEE_CONTACT = 'CREATE_EMPLOYEE_CONTACT',
  UPDATE_EMPLOYEE_CONTACT = 'UPDATE_EMPLOYEE_CONTACT',
  DELETE_EMPLOYEE_CONTACT = 'DELETE_EMPLOYEE_CONTACT'
}
