export enum EMPLOYEE_IDENTIFIER_PERMISSION {
  READ_EMPLOYEE_IDENTIFIER = 'READ_EMPLOYEE_IDENTIFIER',
  CREATE_EMPLOYEE_IDENTIFIER = 'CREATE_EMPLOYEE_IDENTIFIER',
  UPDATE_EMPLOYEE_IDENTIFIER = 'UPDATE_EMPLOYEE_IDENTIFIER',
  DELETE_EMPLOYEE_IDENTIFIER = 'DELETE_EMPLOYEE_IDENTIFIER'
}
