export enum EMPLOYEE_INSURANCE_PERMISSION {
  READ_EMPLOYEE_INSURANCE = 'READ_EMPLOYEE_INSURANCE',
  CREATE_EMPLOYEE_INSURANCE = 'CREATE_EMPLOYEE_INSURANCE',
  UPDATE_EMPLOYEE_INSURANCE = 'UPDATE_EMPLOYEE_INSURANCE',
  DELETE_EMPLOYEE_INSURANCE = 'DELETE_EMPLOYEE_INSURANCE'
}
