export enum COMPANY_STRUCTURE_PERMISSION {
  'READ_COMPANY_STRUCTURE' = 'READ_COMPANY_STRUCTURE',
  'CREATE_COMPANY_STRUCTURE' = 'CREATE_COMPANY_STRUCTURE',
  'UPDATE_COMPANY_STRUCTURE' = 'UPDATE_COMPANY_STRUCTURE',
  'DELETE_COMPANY_STRUCTURE' = 'DELETE_AUTH_COMPANY_STRUCTURE'
}
