export enum EMPLOYEE_QUALIFICATION_PERMISSION {
  'READ_QUALIFICATION' = 'READ_QUALIFICATION',
  'CREATE_QUALIFICATION' = 'CREATE_QUALIFICATION',
  'UPDATE_QUALIFICATION' = 'UPDATE_QUALIFICATION',
  'DELETE_QUALIFICATION' = 'DELETE_QUALIFICATION'
}
