export enum EMPLOYEE_BANK_ACCOUNT_PERMISSION {
  READ_EMPLOYEE_BANK_ACCOUNT = 'READ_EMPLOYEE_BANK_ACCOUNT',
  CREATE_EMPLOYEE_BANK_ACCOUNT = 'CREATE_EMPLOYEE_BANK_ACCOUNT',
  UPDATE_EMPLOYEE_BANK_ACCOUNT = 'UPDATE_EMPLOYEE_BANK_ACCOUNT',
  DELETE_EMPLOYEE_BANK_ACCOUNT = 'DELETE_EMPLOYEE_BANK_ACCOUNT'
}

export enum EMPLOYEE_PAYMENT_METHOD_ACCOUNT_PERMISSION {
  READ_EMPLOYEE_PAYMENT_METHOD_ACCOUNT = 'READ_EMPLOYEE_PAYMENT_METHOD_ACCOUNT',
  CREATE_EMPLOYEE_PAYMENT_METHOD_ACCOUNT = 'CREATE_EMPLOYEE_PAYMENT_METHOD_ACCOUNT',
  UPDATE_EMPLOYEE_PAYMENT_METHOD_ACCOUNT = 'UPDATE_EMPLOYEE_PAYMENT_METHOD_ACCOUNT',
  DELETE_EMPLOYEE_PAYMENT_METHOD_ACCOUNT = 'DELETE_EMPLOYEE_PAYMENT_METHOD_ACCOUNT'
}
