export enum EMPLOYEE_PAYGRADE_PERMISSION {
  'READ_PAY_GRADE' = 'READ_PAY_GRADE',
  'CREATE_PAY_GRADE' = 'CREATE_PAY_GRADE',
  'UPDATE_PAY_GRADE' = 'UPDATE_PAY_GRADE',
  'DELETE_PAY_GRADE' = 'DELETE_PAY_GRADE'
}
