export enum JOB_TITLE_PERMISSION {
  'READ_JOB_TITLE' = 'READ_JOB_TITLE',
  'CREATE_JOB_TITLE' = 'CREATE_JOB_TITLE',
  'UPDATE_JOB_TITLE' = 'UPDATE_JOB_TITLE',
  'DELETE_JOB_TITLE' = 'DELETE_JOB_TITLE'
}
