export enum PAYROLL_BENEFIT_PERMISSION {
  'READ_PAYROLL_BENEFIT' = 'READ_PAYROLL_BENEFIT',
  'CREATE_PAYROLL_BENEFIT' = 'CREATE_PAYROLL_BENEFIT',
  'DELETE_PAYROLL_BENEFIT' = 'DELETE_PAYROLL_BENEFIT',
  'UPDATE_PAYROLL_BENEFIT' = 'UPDATE_PAYROLL_BENEFIT'
}
