export enum SalaryTaxWithheldRankPermission {
  READ_SALARY_TAX_WITHHELD_RANK = 'READ_SALARY_TAX_WITHHELD_RANK',
  CREATE_SALARY_TAX_WITHHELD_RANK = 'CREATE_SALARY_TAX_WITHHELD_RANK',
  DELETE_SALARY_TAX_WITHHELD_RANK = 'DELETE_SALARY_TAX_WITHHELD_RANK',
  UPDATE_SALARY_TAX_WITHHELD_RANK = 'UPDATE_SALARY_TAX_WITHHELD_RANK'
}
