export enum SALARY_COMPONENT_PERMISSION {
  'READ_BENEFIT_COMPONENT' = 'READ_BENEFIT_COMPONENT',
  'CREATE_BENEFIT_COMPONENT' = 'CREATE_BENEFIT_COMPONENT',
  'DELETE_BENEFIT_COMPONENT' = 'DELETE_BENEFIT_COMPONENT',
  'UPDATE_BENEFIT_COMPONENT' = 'UPDATE_BENEFIT_COMPONENT'
}
