export enum STRUCTURE_LOCATION_PERMISSION {
  'READ_STRUCTURE_LOCATION' = 'READ_STRUCTURE_LOCATION',
  'CREATE_STRUCTURE_LOCATION' = 'CREATE_STRUCTURE_LOCATION',
  'UPDATE_STRUCTURE_LOCATION' = 'UPDATE_STRUCTURE_LOCATION',
  'DELETE_STRUCTURE_LOCATION' = 'DELETE_STRUCTURE_LOCATION'
}
