export enum STRUCTURE_POSITION_PERMISSION {
  'READ_STRUCTURE_POSITION' = 'READ_STRUCTURE_POSITION',
  'CREATE_STRUCTURE_POSITION' = 'CREATE_STRUCTURE_POSITION',
  'UPDATE_STRUCTURE_POSITION' = 'UPDATE_STRUCTURE_POSITION',
  'DELETE_STRUCTURE_POSITION' = 'DELETE_STRUCTURE_POSITION'
}
