export enum VACCINATION_NAME_PERMISSION {
  'READ_VACCINATION_NAME' = 'READ_VACCINATION_NAME',
  'CREATE_VACCINATION_NAME' = 'CREATE_VACCINATION_NAME',
  'UPDATE_VACCINATION_NAME' = 'UPDATE_VACCINATION_NAME',
  'DELETE_VACCINATION_NAME' = 'DELETE_KEY_VALUE'
}
