import * as PERMISSION from '../../../../shared-resources/ts/enum/permission';

export const PERMISSION_LIST = {
  GET_PERMISSION_LIST: [
    PERMISSION.PERMISSION.READ_PERMISSION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ],
  DELETE_PERMISSION_LIST: [
    PERMISSION.PERMISSION.DELETE_PERMISSION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  UPDATE_PERMISSION_LIST: [
    PERMISSION.PERMISSION.UPDATE_PERMISSION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  CREATE_PERMISSION_LIST: [
    PERMISSION.PERMISSION.CREATE_PERMISSION,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ]
};
