export { EMPLOYEE_MASTER_INFORMATION_PERMISSION } from './employee/employee-master-information.enum';
export { EMPLOYEE_MOVEMENT_PERMISSION } from './employee/employee-movement.enum';
export { EMPLOYEE_RESIGNATION_PERMISSION } from './employee/employee-resignation.enum';
export { EMPLOYEE_STATUS_PERMISSION } from './employee/employee-status.enum';
export { EMPLOYEE_WARNING_PERMISSION } from './employee/employee-warning.enum';
export { EMPLOYEE_PAYGRADE_PERMISSION } from './employee/employee-paygarde.enum';
export { EMPLOYEE_QUALIFICATION_PERMISSION } from './employee/employee-qualification.enum';
export { JOB_TITLE_PERMISSION } from './employee/job-title.enum';
export { CODE_VALUE_PERMISSION } from './employee/code-value.enum';
export { SPECIAL_PERMISSION } from './special/special.enum';
export { AUTHENTICATION_PERMISSION } from './authentication/authentication.enum';
export { PERMISSION } from './authentication/permission.enum';
export { ROLE_PERMISSION_PERMISSION } from './authentication/role-permission.enum';
export { ROLE_PERMISSION } from './authentication/role.enum';
export { USER_PERMISSION } from './authentication/user.enum';
export { AUDIT_LOG_PERMISSION } from './authentication/audit-log.enum';
export { GLOBAL_CONFIGURATION_PERMISSION } from './authentication/global-configuration.enum';
export { PositionLevelPermissionEnum } from './employee/position-level.enum';
export { PAYMENT_METHOD_PERMISSION } from './employee/bank-name.enum';
export { VACCINATION_NAME_PERMISSION } from './employee/vaccination-name.enum';
export { STRUCTURE_LOCATION_PERMISSION } from './employee/structure-location.enum';
export { STRUCTURE_OUTLET_PERMISSION } from './employee/structure-outlet.enum';
export { STRUCTURE_DEPARTMENT_PERMISSION } from './employee/structure-department.enum';
export { STRUCTURE_POSITION_PERMISSION } from './employee/structure-position.enum';
export { COMPANY_STRUCTURE_PERMISSION } from './employee/employee-company-structure.enum';
export { EMPLOYEE_VACCINATION_PERMISSION } from './employee/employee-vaccination.enum';
export { REQUEST_WORKFLOW_TYPE_PERMISSION as REQUEST_WORK_FLOW_TYPE_PERMISSION } from './authentication/request-work-flow-type.enum';
export { COMPANY_STRUCTURE_COMPONENT_PERMISSION } from './employee/company-structure-component.enum';
export { PAYROLL_BENEFIT_ADJUSTMENT_PERMISSION } from './employee/payroll-benefit-adjustment.enum';

//* Attendance
export { OVERTIME_REQUEST_TYPE_PERMISSION } from './attendance/overtime-request-type.enum';
export { PUBLIC_HOLIDAY_PERMISSION } from './attendance/public-holiday.enum';
export { ATTENDANCE_RECORD_PERMISSION } from './attendance/attendance-record.enum';
