export enum SALARY_COMPONENT_TYPE_PERMISSION {
  READ_BENEFIT_COMPONENT_TYPE = 'READ_BENEFIT_COMPONENT_TYPE',
  CREATE_BENEFIT_COMPONENT_TYPE = 'CREATE_BENEFIT_COMPONENT_TYPE',
  UPDATE_BENEFIT_COMPONENT_TYPE = 'UPDATE_BENEFIT_COMPONENT_TYPE',
  DELETE_BENEFIT_COMPONENT_TYPE = 'DELETE_BENEFIT_COMPONENT_TYPE'
}
