export enum PAYMENT_METHOD_PERMISSION {
  'READ_PAYMENT_METHOD' = 'READ_PAYMENT_METHOD',
  'CREATE_PAYMENT_METHOD' = 'CREATE_PAYMENT_METHOD',
  'UPDATE_PAYMENT_METHOD' = 'UPDATE_PAYMENT_METHOD',
  'DELETE_PAYMENT_METHOD' = 'DELETE_PAYMENT_METHOD'
}
