export enum BenefitAdjustmentTypePermissionEnum {
  READ_BENEFIT_ADJUSTMENT_TYPE = 'READ_BENEFIT_ADJUSTMENT_TYPE',
  CREATE_BENEFIT_ADJUSTMENT_TYPE = 'CREATE_BENEFIT_ADJUSTMENT_TYPE',
  DELETE_BENEFIT_ADJUSTMENT_TYPE = 'DELETE_BENEFIT_ADJUSTMENT_TYPE',
  UPDATE_BENEFIT_ADJUSTMENT_TYPE = 'UPDATE_BENEFIT_ADJUSTMENT_TYPE'
}
