export enum BENEFIT_INCREASEMENT_POLICY_PERMISSION {
  READ_BENEFIT_INCREASEMENT_POLICY = 'READ_BENEFIT_INCREASEMENT_POLICY',
  CREATE_BENEFIT_INCREASEMENT_POLICY = 'CREATE_BENEFIT_INCREASEMENT_POLICY',
  DELETE_BENEFIT_INCREASEMENT_POLICY = 'DELETE_BENEFIT_INCREASEMENT_POLICY',
  UPDATE_BENEFIT_INCREASEMENT_POLICY = 'UPDATE_BENEFIT_INCREASEMENT_POLICY'
}
