export enum CRUD_PAYROLL_POST_PROBATION_PERMISSION {
  'READ_CRUD_PAYROLL_POST_PROBATION' = 'READ_CRUD_PAYROLL_POST_PROBATION',
  'CREATE_CRUD_PAYROLL_POST_PROBATION' = 'CREATE_CRUD_PAYROLL_POST_PROBATION',
  'DELETE_CRUD_PAYROLL_POST_PROBATION' = 'DELETE_CRUD_PAYROLL_POST_PROBATION',
  'UPDATE_CRUD_PAYROLL_POST_PROBATION' = 'UPDATE_CRUD_PAYROLL_POST_PROBATION'
}

export enum PAYROLL_POST_PROBATION_PERMISSION {
  READ_PAYROLL_POST_PROBATION = 'READ_PAYROLL_POST_PROBATION',
  CREATE_PAYROLL_POST_PROBATION = 'CREATE_PAYROLL_POST_PROBATION',
  DELETE_PAYROLL_POST_PROBATION = 'DELETE_PAYROLL_POST_PROBATION',
  UPDATE_PAYROLL_POST_PROBATION = 'UPDATE_PAYROLL_POST_PROBATION'
}
