export enum EMPLOYEE_WORKING_SCHEDULE_PERMISSION {
  'READ_EMPLOYEE_WORKING_SCHEDULE' = 'READ_EMPLOYEE_WORKING_SCHEDULE',
  'CREATE_EMPLOYEE_WORKING_SCHEDULE' = 'CREATE_EMPLOYEE_WORKING_SCHEDULE',
  'UPDATE_EMPLOYEE_WORKING_SCHEDULE' = 'UPDATE_EMPLOYEE_WORKING_SCHEDULE',
  'DELETE_EMPLOYEE_WORKING_SCHEDULE' = 'DELETE_EMPLOYEE_WORKING_SCHEDULE'
}
