export enum EMPLOYEE_EDUCATION_PERMISSION {
  READ_EMPLOYEE_EDUCATION = 'READ_EMPLOYEE_EDUCATION',
  CREATE_EMPLOYEE_EDUCATION = 'CREATE_EMPLOYEE_EDUCATION',
  UPDATE_EMPLOYEE_EDUCATION = 'UPDATE_EMPLOYEE_EDUCATION',
  DELETE_EMPLOYEE_EDUCATION = 'DELETE_EMPLOYEE_EDUCATION'
}
