export enum EMPLOYEE_RESIGNATION_PERMISSION {
  'READ_EMPLOYEE_RESIGNATION' = 'READ_EMPLOYEE_RESIGNATION',
  'CREATE_EMPLOYEE_RESIGNATION' = 'CREATE_EMPLOYEE_RESIGNATION',
  'UPDATE_EMPLOYEE_RESIGNATION' = 'UPDATE_EMPLOYEE_RESIGNATION',
  'DELETE_EMPLOYEE_RESIGNATION' = 'DELETE_EMPLOYEE_RESIGNATION'
}
