export enum EMPLOYEE_TRAINING_PERMISSION {
  READ_EMPLOYEE_TRAINING = 'READ_EMPLOYEE_TRAINING',
  CREATE_EMPLOYEE_TRAINING = 'CREATE_EMPLOYEE_TRAINING',
  UPDATE_EMPLOYEE_TRAINING = 'UPDATE_EMPLOYEE_TRAINING',
  DELETE_EMPLOYEE_TRAINING = 'DELETE_EMPLOYEE_TRAINING'
}
