export enum EMPLOYEE_VACCINATION_PERMISSION {
  READ_EMPLOYEE_VACCINATION = 'READ_EMPLOYEE_VACCINATION',
  CREATE_EMPLOYEE_VACCINATION = 'CREATE_EMPLOYEE_VACCINATION',
  UPDATE_EMPLOYEE_VACCINATION = 'UPDATE_EMPLOYEE_VACCINATION',
  DELETE_EMPLOYEE_VACCINATION = 'DELETE_EMPLOYEE_VACCINATION'
}
