export enum EMPLOYEE_MOVEMENT_PERMISSION {
  'READ_EMPLOYEE_MOVEMENT' = 'READ_EMPLOYEE_MOVEMENT',
  'CREATE_EMPLOYEE_MOVEMENT' = 'CREATE_EMPLOYEE_MOVEMENT',
  'UPDATE_EMPLOYEE_MOVEMENT' = 'UPDATE_EMPLOYEE_MOVEMENT',
  'DELETE_EMPLOYEE_MOVEMENT' = 'DELETE_EMPLOYEE_MOVEMENT'
}
