export enum EMPLOYEE_WARNING_PERMISSION {
  'READ_EMPLOYEE_WARNING' = 'READ_EMPLOYEE_WARNING',
  'CREATE_EMPLOYEE_WARNING' = 'CREATE_EMPLOYEE_WARNING',
  'UPDATE_EMPLOYEE_WARNING' = 'UPDATE_EMPLOYEE_WARNING',
  'DELETE_EMPLOYEE_WARNING' = 'DELETE_EMPLOYEE_WARNING'
}
