export enum EMPLOYEE_STATUS_PERMISSION {
  'READ_EMPLOYEE_STATUS' = 'READ_EMPLOYEE_STATUS',
  'CREATE_EMPLOYEE_STATUS' = 'CREATE_EMPLOYEE_STATUS',
  'UPDATE_EMPLOYEE_STATUS' = 'UPDATE_EMPLOYEE_STATUS',
  'DELETE_EMPLOYEE_STATUS' = 'DELETE_EMPLOYEE_STATUS'
}
