export enum INSURANCE_PERMISSION {
  'READ_INSURANCE' = 'READ_INSURANCE',
  'CREATE_INSURANCE' = 'CREATE_INSURANCE',
  'UPDATE_INSURANCE' = 'UPDATE_INSURANCE',
  'DELETE_INSURANCE' = 'DELETE_INSURANCE'
}
