export enum PAYROLL_REPORT_PERMISSION {
  'READ_PAYROLL_REPORT' = 'READ_PAYROLL_REPORT',
  'CREATE_PAYROLL_REPORT' = 'CREATE_PAYROLL_REPORT',
  'DELETE_PAYROLL_REPORT' = 'DELETE_PAYROLL_REPORT',
  'UPDATE_PAYROLL_REPORT' = 'UPDATE_PAYROLL_REPORT'
}
