export enum PayrollCycleConfigurationPermissionEnum {
  READ_PAYROLL_CYCLE_CONFIGURATION = 'READ_PAYROLL_CYCLE_CONFIGURATION',
  UPDATE_PAYROLL_CYCLE_CONFIGURATION = 'UPDATE_PAYROLL_CYCLE_CONFIGURATION'
}
