export enum PAYROLL_DEDUCTION_PERMISSION {
  'READ_PAYROLL_DEDUCTION' = 'READ_PAYROLL_DEDUCTION',
  'CREATE_PAYROLL_DEDUCTION' = 'CREATE_PAYROLL_DEDUCTION',
  'DELETE_PAYROLL_DEDUCTION' = 'DELETE_PAYROLL_DEDUCTION',
  'UPDATE_PAYROLL_DEDUCTION' = 'UPDATE_PAYROLL_DEDUCTION'
}
