export enum PAYROLL_DEDUCTION_TYPE_PERMISSION {
  'READ_PAYROLL_DEDUCTION_TYPE' = 'READ_PAYROLL_DEDUCTION_TYPE',
  'CREATE_PAYROLL_DEDUCTION_TYPE' = 'CREATE_PAYROLL_DEDUCTION_TYPE',
  'DELETE_PAYROLL_DEDUCTION_TYPE' = 'DELETE_PAYROLL_DEDUCTION_TYPE',
  'UPDATE_PAYROLL_DEDUCTION_TYPE' = 'UPDATE_PAYROLL_DEDUCTION_TYPE'
}
