export enum PAYROLL_BENEFIT_ADJUSTMENT_PERMISSION {
  'READ_PAYROLL_BENEFIT_ADJUSTMENT' = 'READ_PAYROLL_BENEFIT_ADJUSTMENT',
  'CREATE_PAYROLL_BENEFIT_ADJUSTMENT' = 'CREATE_PAYROLL_BENEFIT_ADJUSTMENT',
  'UPDATE_PAYROLL_BENEFIT_ADJUSTMENT' = 'UPDATE_PAYROLL_BENEFIT_ADJUSTMENT',
  'DELETE_PAYROLL_BENEFIT_ADJUSTMENT' = 'DELETE_PAYROLL_BENEFIT_ADJUSTMENT'
}
