export enum PositionLevelPermissionEnum {
  'READ_POSITION_LEVEL' = 'READ_POSITION_LEVEL',
  'CREATE_POSITION_LEVEL' = 'CREATE_POSITION_LEVEL',
  'DELETE_POSITION_LEVEL' = 'DELETE_POSITION_LEVEL',
  'UPDATE_POSITION_LEVEL' = 'UPDATE_POSITION_LEVEL'
}

export enum PositionLevelTitleEnum {
  MANAGER = 'MANAGER',
  CHIEF = 'CHIEF',
  HEAD_OF_DEPARTMENT = 'HEAD OF DEPARTMENT',
  SUPERVISOR = 'SUPERVISOR',
  SENIOR_OFFICER = 'SENIOR OFFICER',
  CREW = 'CREW',
  INTERN = 'INTERN',
  OFFICER = 'OFFICER',
  DEPUTY_MANAGER = 'DEPUTY MANAGER'
}
