export enum SALARY_COMPONENT_TYPE_PERMISSION {
  'READ_SALARY_COMPONENT_TYPE' = 'READ_SALARY_COMPONENT_TYPE',
  'CREATE_SALARY_COMPONENT_TYPE' = 'CREATE_SALARY_COMPONENT_TYPE',
  'DELETE_SALARY_COMPONENT_TYPE' = 'DELETE_SALARY_COMPONENT_TYPE',
  'UPDATE_SALARY_COMPONENT_TYPE' = 'UPDATE_SALARY_COMPONENT_TYPE'
}
