export enum STRUCTURE_DEPARTMENT_PERMISSION {
  'READ_STRUCTURE_DEPARTMENT' = 'READ_STRUCTURE_DEPARTMENT',
  'CREATE_STRUCTURE_DEPARTMENT' = 'CREATE_STRUCTURE_DEPARTMENT',
  'UPDATE_STRUCTURE_DEPARTMENT' = 'UPDATE_STRUCTURE_DEPARTMENT',
  'DELETE_STRUCTURE_DEPARTMENT' = 'DELETE_STRUCTURE_DEPARTMENT'
}
