export enum STRUCTURE_OUTLET_PERMISSION {
  'READ_STRUCTURE_OUTLET' = 'READ_STRUCTURE_OUTLET',
  'CREATE_STRUCTURE_OUTLET' = 'CREATE_STRUCTURE_OUTLET',
  'UPDATE_STRUCTURE_OUTLET' = 'UPDATE_STRUCTURE_OUTLET',
  'DELETE_STRUCTURE_OUTLET' = 'DELETE_KEY_VALUE'
}
