export enum WORKING_SHIFT_PERMISSION {
  READ_WORKING_SHIFT = 'READ_WORKING_SHIFT',
  CREATE_WORKING_SHIFT = 'CREATE_WORKING_SHIFT',
  UPDATE_WORKING_SHIFT = 'UPDATE_WORKING_SHIFT',
  DELETE_WORKING_SHIFT = 'DELETE_WORKING_SHIFT'
}
