export enum ReportEnum {
  DAILY_EMPLOYEE_ATTENDANCE = 1,
  REPORT_EMPLOYEE_MOVEMENT = 2,
  REPORT_TOTAL_EMPLOYEE = 3,
  QUICK_REQUEST_REPORT = 4,
  TOTAL_EMPLOYEE_IN_LOCATIONS = 5,
  REQUEST_APPROVAL = 6,
  REPORT_EMPLOYEE_PERSONAL_INFO = 7,
  LEAVE_REMAINING_REPORT = 8,
  REPORT_ATTENDANCE_REMINDER = 9,
  REPORT_EMPLOYEE_REMINDER = 10
}
