export const EMPLOYEE_LEAVE_REQUEST_HEADERS = [
  'NO*',
  'ACCOUNT NO*',
  'EMPLOYEE',
  'LEAVE_REQUEST_TYPE*',
  'DURATION TYPE*',
  'FROM DATE*',
  'TO DATE*',
  'LEAVE DURATION*',
  'IS SPECIAL LEAVE',
  'RESULT',
  'MESSAGE'
];
