export const EMPLOYEE_INFORMATION_HEADER = [
  'Id',
  'Employee Status',
  'Account Number',
  'Finger Print Id',
  'Employment Status',
  'En First Name',
  'En Last Name',
  'Kh First Name',
  'Kh Last Name',
  'Gender',
  'Location',
  'Outlet',
  'Department',
  'Position',
  'Is Default Position',
  'Start Date',
  'Post Probation Date',
  'Resign Date',
  'Contract Type',
  'Contract Period Start Date',
  'Contract Period End Date',
  'Employment Type',
  'Working Shift Type',
  'Working Shift',
  'Date of Birth',
  'Age',
  'Place of Birth',
  'Nationality',
  'Contact Number',
  'Email',
  'Document Type',
  'Document Identifier',
  'Contact Number',
  'Contact Relationship Ip',
  'Marital Status',
  'Spouse',
  'Spouse Occupation',
  'Number of children',
  'Home Number',
  'Street Number',
  'Village',
  'Province/City',
  'District/Khan',
  'Commune/Sankat',
  'Tax Responsible',
  'Payment Method Name',
  'Payment Method Account Number',
  'Default Payment Method Acc',
  'Insurance Name',
  'Insurance Card Number',
  'Vaccination Name',
  'Vaccination Card Number',
  'Education Type',
  'Institution Name',
  'Major',
  'Start Date',
  'Complete Date',
  'Language',
  'Skill',
  'Traning'
];
