export enum TypeEnum {
  REQUESTERS = 'REQUESTERS',
  REQUEST_FORS = 'REQUEST_FORS',
  FIRST_APPROVALS = 'FIRST_APPROVALS',
  SECOND_APPROVALS = 'SECOND_APPROVALS',
  ACKNOWLEDGERS = 'ACKNOWLEDGERS'
}
