export enum DAY_OFF_REQUEST_PERMISSION {
  READ_DAY_OFF_REQUEST = 'READ_DAY_OFF_REQUEST',
  CREATE_DAY_OFF_REQUEST = 'CREATE_DAY_OFF_REQUEST',
  UPDATE_DAY_OFF_REQUEST = 'UPDATE_DAY_OFF_REQUEST',
  DELETE_DAY_OFF_REQUEST = 'DELETE_DAY_OFF_REQUEST'
}
