export enum LEAVE_REQUEST_TYPE_PERMISSION {
  READ_LEAVE_REQUEST_TYPE = 'READ_LEAVE_REQUEST_TYPE',
  CREATE_LEAVE_REQUEST_TYPE = 'CREATE_LEAVE_REQUEST_TYPE',
  UPDATE_LEAVE_REQUEST_TYPE = 'UPDATE_LEAVE_REQUEST_TYPE',
  DELETE_LEAVE_REQUEST_TYPE = 'DELETE_LEAVE_REQUEST_TYPE'
}
