export enum MISSION_REQUEST_PERMISSION {
  READ_MISSION_REQUEST = 'READ_MISSION_REQUEST',
  CREATE_MISSION_REQUEST = 'CREATE_MISSION_REQUEST',
  UPDATE_MISSION_REQUEST = 'UPDATE_MISSION_REQUEST',
  DELETE_MISSION_REQUEST = 'DELETE_MISSION_REQUEST'
}
