import * as PERMISSION from '../../../../shared-resources/ts/enum/permission';

export const USER_PERMISSION = {
  GET_USER: [
    PERMISSION.USER_PERMISSION.READ_USER,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION,
    PERMISSION.SPECIAL_PERMISSION.READ_ALL_FUNCTION
  ],
  DELETE_USER: [
    PERMISSION.USER_PERMISSION.DELETE_USER,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  UPDATE_USER: [
    PERMISSION.USER_PERMISSION.UPDATE_USER,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ],
  CREATE_USER: [
    PERMISSION.USER_PERMISSION.CREATE_USER,
    PERMISSION.SPECIAL_PERMISSION.ALL_FUNCTION
  ]
};
