export enum ATTENDANCE_RECORD_PERMISSION {
  READ_ATTENDANCE_RECORD = 'READ_ATTENDANCE_RECORD',
  CREATE_ATTENDANCE_RECORD = 'CREATE_ATTENDANCE_RECORD',
  UPDATE_ATTENDANCE_RECORD = 'UPDATE_ATTENDANCE_RECORD',
  DELETE_ATTENDANCE_RECORD = 'DELETE_ATTENDANCE_RECORD'
}
