export enum BORROW_OR_PAYBACK_PERMISSION {
  READ_BORROW_OR_PAYBACK = 'READ_BORROW_OR_PAYBACK',
  CREATE_BORROW_OR_PAYBACK = 'CREATE_BORROW_OR_PAYBACK',
  UPDATE_BORROW_OR_PAYBACK = 'UPDATE_BORROW_OR_PAYBACK',
  DELETE_BORROW_OR_PAYBACK = 'DELETE_BORROW_OR_PAYBACK'
}
