export enum OVERTIME_REQUEST_PERMISSION {
  READ_OVERTIME_REQUEST = 'READ_OVERTIME_REQUEST',
  CREATE_OVERTIME_REQUEST = 'CREATE_OVERTIME_REQUEST',
  UPDATE_OVERTIME_REQUEST = 'UPDATE_OVERTIME_REQUEST',
  DELETE_OVERTIME_REQUEST = 'DELETE_OVERTIME_REQUEST'
}
