export enum PUBLIC_HOLIDAY_PERMISSION {
  READ_PUBLIC_HOLIDAY = 'READ_PUBLIC_HOLIDAY',
  CREATE_PUBLIC_HOLIDAY = 'CREATE_PUBLIC_HOLIDAY',
  UPDATE_PUBLIC_HOLIDAY = 'UPDATE_PUBLIC_HOLIDAY',
  DELETE_PUBLIC_HOLIDAY = 'DELETE_PUBLIC_HOLIDAY'
}
